apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app-nonprod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mahmoudhussein155-30/nti-project.git
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values-nonprod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: voting-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
